config/routes.rb
Rails.application.routes.draw do
  get 'members/index'
  get 'members/show'
  get 'members/new'
  get 'members/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
    
  end

  def new
    @member = Member.new
  end

  def create
    member = Member.create(member_params)
    redirect_to members_path
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)

    redirect_to member_path(@member)
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    redirect_to members_path
  end

  private

  def member_params
    params.require(:member).permit(:name, :bio, :role)
  end

  def current_member
    @member = Member.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemberApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<h3>Update Member Details</h3>
<%= form_with model: @member do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :bio, placeholder: "bio" %>
  <%= form.text_field :role, placeholder: "role" %>
  <%= form.submit %>
<% end %>

app/views/members/index.html.erb
<table>
  <% @members.each do |member| %>
    <tr>
      <td><%= link_to member.name, member_path(member) %></td>
      <td><%= button_to 'Edit', edit_member_path(member), method: 'get' %></td>
      <td><%= button_to 'Remove', member_path(member), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to "Add a New Member", new_member_path %>

app/views/members/new.html.erb
<h3>Create a Member</h3>
<%= form_with model: @member do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :bio, placeholder: "bio" %>
  <%= form.text_field :role, placeholder: "role" %>
  <%= form.submit %>
<% end %>

<!-- <%= form_for @member do |form| %>
  <%= form.text_field :name, placeholder: 'name' %>
  <%= form.text_field :bio, placeholder: 'bio' %>
  <%= form.text_field :role, placeholder: 'role' %>
  <%= form.submit %>
<% end %> -->

app/views/members/show.html.erb
<h1><%= @member.name %></h1>
<p><%= @member.bio %></p>